### ISSUE TITLE
not loading any repositories

### ISSUE THREAD

**Issue by richcoughlan** [Labhk/BoltSync-Issues#3]
not loading any repositories

**Comment by Labhk** [comment]
Hi, you can try signing out  and then signIn again,
![image](https://github.com/user-attachments/assets/3b9839b6-ff63-492d-b05d-330eeddee79a)

if u see this then u need to signOut and then again signIn

**Comment by richcoughlan** [comment]
did that - I only see github repositories from 13 hrs ago whereas I have been updating every 30 mins

**Comment by Labhk** [comment]
then u can do one thing then go to the github install button 
![image](https://github.com/user-attachments/assets/d58ea1f0-09c3-4dd0-839b-8ff7e156a027)

then instead of all repo u select repo u want then continue as it is.
signOut and signIn again.

![image](https://github.com/user-attachments/assets/938f6aa1-97d1-4274-a3f3-5cf217e7c6f3)

I think this is due to github API limitation,
